### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by seanfrasure** [JavascriptFTW/JavascriptFTW.github.io#1]
-Your favicon is 2048...
- Your title is 'Name'

**Comment by JavascriptFTW** [comment]
It's in progress. At least I do

**Comment by JavascriptFTW** [comment]
It's in progress. Closed this issue by accident also.

**Comment by JavascriptFTW** [comment]
Fixed this issue after redoing the entire site (not **just** to fix this issue... :stuck_out_tongue: )
I've disabled caching so something like this shouldn't happen again. It would probably be a better idea to just make it so that the cache refreshes after a certain time. Anywho I restyled the entire site and made actually look like I put work into it if you wanna check it out.
Closing this issue.

**Comment by seanfrasure** [comment]
Looks nice
